Repository dsccommunity/ActiveDirectoryDsc, pull requests merged in 2019-07, with the labels that each got.

#405 xActiveDirectory: Add Auto-Generated 'about_<DSCResource>.help.txt' Files for all Resources
  CHANGELOG.md
  DSCResources/MSFT_xADComputer/en-US/about_xADComputer.help.txt
  DSCResources/MSFT_xADDomain/en-US/about_xADDomain.help.txt
  DSCResources/MSFT_xADDomainController/en-US/about_xADDomainController.help.txt
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/en-US/about_xADDomainDefaultPasswordPolicy.help.txt
  DSCResources/MSFT_xADDomainTrust/en-US/about_xADDomainTrust.help.txt
  DSCResources/MSFT_xADForestProperties/en-US/about_xADForestProperties.help.txt
  DSCResources/MSFT_xADGroup/en-US/about_xADGroup.help.txt
  DSCResources/MSFT_xADKDSKey/en-US/about_xADKDSKey.help.txt
  DSCResources/MSFT_xADManagedServiceAccount/en-US/about_xADManagedServiceAccount.help.txt
  DSCResources/MSFT_xADObjectEnabledState/en-US/about_xADObjectEnabledState.help.txt
  DSCResources/MSFT_xADObjectPermissionEntry/en-US/about_xADObjectPermissionEntry.help.txt
  DSCResources/MSFT_xADOrganizationalUnit/en-US/about_xADOrganizationalUnit.help.txt
  DSCResources/MSFT_xADRecycleBin/en-US/about_xADRecycleBin.help.txt
  DSCResources/MSFT_xADReplicationSite/en-US/about_xADReplicationSite.help.txt
  DSCResources/MSFT_xADReplicationSiteLink/en-US/about_xADReplicationSiteLink.help.txt
  DSCResources/MSFT_xADReplicationSubnet/en-US/about_xADReplicationSubnet.help.txt
  DSCResources/MSFT_xADServicePrincipalName/en-US/about_xADServicePrincipalName.help.txt
  DSCResources/MSFT_xADUser/en-US/about_xADUser.help.txt
  DSCResources/MSFT_xWaitForADDomain/en-US/about_xWaitForADDomain.help.txt
Labels: needs review

#411 xADComputer: Fix Example 3-AddComputerAccountSpecificPath_Config GUID
  CHANGELOG.md
  Examples/Resources/xADComputer/3-AddComputerAccountSpecificPath_Config.ps1
Labels: needs review

#413 xADOrganizationalUnit: Catch Exception When the Path Property specifies a Non-Existing Path
  CHANGELOG.md
  DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.psm1
  DSCResources/MSFT_xADOrganizationalUnit/en-US/MSFT_xADOrganizationalUnit.strings.psd1
  Tests/Unit/MSFT_xADOrganizationalUnit.Tests.ps1
Labels: needs review

#412 xADUser: Fix CN/Path Concurrent Change and Empty String Property on Creation Exceptions
  CHANGELOG.md
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
Labels: waiting for code fix

#417 xADUser: Fix ChangePasswordAtLogon Property to be only set to True at User Creation
  CHANGELOG.md
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
  DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof
  Tests/Unit/MSFT_xADUser.Tests.ps1
Labels: waiting for code fix

#418 xActiveDirectory: Remove old helper functions
  CHANGELOG.md
  DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1
  DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
  Modules/xActiveDirectory.Common/en-US/xActiveDirectory.Common.strings.psd1
  Modules/xActiveDirectory.Common/xActiveDirectory.Common.psm1
  Tests/Unit/MSFT_xADDomain.Tests.ps1
  Tests/Unit/MSFT_xADKDSKey.Tests.ps1
  Tests/Unit/MSFT_xADRecycleBin.Tests.ps1
  Tests/Unit/MSFT_xADUser.Tests.ps1
  Tests/Unit/xActiveDirectory.Common.Tests.ps1
Labels: needs review

#428 xActiveDirectory: Fix various documentation issues
  CHANGELOG.md
  DSCResources/MSFT_xADComputer/MSFT_xADComputer.schema.mof
  DSCResources/MSFT_xADComputer/en-US/about_xADComputer.help.txt
  DSCResources/MSFT_xADDomain/MSFT_xADDomain.schema.mof
  DSCResources/MSFT_xADDomain/en-US/MSFT_xADDomain.strings.psd1
  DSCResources/MSFT_xADDomain/en-US/about_xADDomain.help.txt
  DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.schema.mof
  DSCResources/MSFT_xADDomainController/en-US/MSFT_xADDomainController.strings.psd1
  DSCResources/MSFT_xADDomainController/en-US/about_xADDomainController.help.txt
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/MSFT_xADDomainDefaultPasswordPolicy.schema.mof
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/en-US/MSFT_xADDomainDefaultPasswordPolicy.strings.psd1
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/en-US/about_xADDomainDefaultPasswordPolicy.help.txt
  DSCResources/MSFT_xADForestProperties/MSFT_xADForestProperties.schema.mof
  DSCResources/MSFT_xADForestProperties/en-US/MSFT_xADForestProperties.strings.psd1
  DSCResources/MSFT_xADForestProperties/en-US/about_xADForestProperties.help.txt
  DSCResources/MSFT_xADGroup/MSFT_xADGroup.schema.mof
  DSCResources/MSFT_xADGroup/en-US/MSFT_xADGroup.strings.psd1
  DSCResources/MSFT_xADGroup/en-US/about_xADGroup.help.txt
  DSCResources/MSFT_xADKDSKey/MSFT_xADKDSKey.schema.mof
  DSCResources/MSFT_xADKDSKey/en-US/about_xADKDSKey.help.txt
  DSCResources/MSFT_xADManagedServiceAccount/MSFT_xADManagedServiceAccount.schema.mof
  DSCResources/MSFT_xADManagedServiceAccount/en-US/about_xADManagedServiceAccount.help.txt
  DSCResources/MSFT_xADObjectPermissionEntry/MSFT_xADObjectPermissionEntry.schema.mof
  DSCResources/MSFT_xADObjectPermissionEntry/en-US/about_xADObjectPermissionEntry.help.txt
  DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.schema.mof
  DSCResources/MSFT_xADOrganizationalUnit/en-US/MSFT_xADOrganizationalUnit.strings.psd1
  DSCResources/MSFT_xADOrganizationalUnit/en-US/about_xADOrganizationalUnit.help.txt
  DSCResources/MSFT_xADRecycleBin/MSFT_xADRecycleBin.schema.mof
  DSCResources/MSFT_xADRecycleBin/en-US/MSFT_xADRecycleBin.strings.psd1
  DSCResources/MSFT_xADRecycleBin/en-US/about_xADRecycleBin.help.txt
  DSCResources/MSFT_xADReplicationSite/MSFT_xADReplicationSite.schema.mof
  DSCResources/MSFT_xADReplicationSite/en-US/MSFT_xADReplicationSite.strings.psd1
  DSCResources/MSFT_xADReplicationSite/en-US/about_xADReplicationSite.help.txt
  DSCResources/MSFT_xADReplicationSiteLink/MSFT_xADReplicationSiteLink.schema.mof
  DSCResources/MSFT_xADReplicationSiteLink/en-US/MSFT_xADReplicationSiteLink.strings.psd1
  DSCResources/MSFT_xADReplicationSiteLink/en-US/about_xADReplicationSiteLink.help.txt
  DSCResources/MSFT_xADReplicationSubnet/MSFT_xADReplicationSubnet.schema.mof
  DSCResources/MSFT_xADReplicationSubnet/en-US/MSFT_xADReplicationSubnet.strings.psd1
  DSCResources/MSFT_xADReplicationSubnet/en-US/about_xADReplicationSubnet.help.txt
  DSCResources/MSFT_xADServicePrincipalName/MSFT_xADServicePrincipalName.schema.mof
  DSCResources/MSFT_xADServicePrincipalName/en-US/MSFT_xADServicePrincipalName.strings.psd1
  DSCResources/MSFT_xADServicePrincipalName/en-US/about_xADServicePrincipalName.help.txt
  DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof
  DSCResources/MSFT_xADUser/en-US/MSFT_xADUser.strings.psd1
  DSCResources/MSFT_xADUser/en-US/about_xADUser.help.txt
  DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.schema.mof
  DSCResources/MSFT_xWaitForADDomain/en-US/MSFT_xWaitForADDomain.strings.psd1
  DSCResources/MSFT_xWaitForADDomain/en-US/about_xWaitForADDomain.help.txt
  Tests/Unit/MSFT_xADServicePrincipalName.Tests.ps1
Labels: needs review

#423 xADDomainTrust: Refactor resource and add tests
  CHANGELOG.md
  DSCResources/MSFT_xADComputer/en-US/about_xADComputer.help.txt
  DSCResources/MSFT_xADDomain/en-US/about_xADDomain.help.txt
  DSCResources/MSFT_xADDomainController/en-US/about_xADDomainController.help.txt
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/en-US/about_xADDomainDefaultPasswordPolicy.help.txt
  DSCResources/MSFT_xADDomainTrust/MSFT_xADDomainTrust.psm1
  DSCResources/MSFT_xADDomainTrust/MSFT_xADDomainTrust.schema.mof
  DSCResources/MSFT_xADDomainTrust/README.md
  DSCResources/MSFT_xADDomainTrust/en-US/MSFT_xADDomainTrust.strings.psd1
  DSCResources/MSFT_xADDomainTrust/en-US/about_xADDomainTrust.help.txt
  DSCResources/MSFT_xADForestProperties/en-US/about_xADForestProperties.help.txt
  DSCResources/MSFT_xADGroup/en-US/about_xADGroup.help.txt
  DSCResources/MSFT_xADKDSKey/en-US/about_xADKDSKey.help.txt
  DSCResources/MSFT_xADManagedServiceAccount/en-US/about_xADManagedServiceAccount.help.txt
  DSCResources/MSFT_xADObjectEnabledState/en-US/about_xADObjectEnabledState.help.txt
  DSCResources/MSFT_xADObjectPermissionEntry/en-US/about_xADObjectPermissionEntry.help.txt
  DSCResources/MSFT_xADOrganizationalUnit/en-US/about_xADOrganizationalUnit.help.txt
  DSCResources/MSFT_xADRecycleBin/en-US/about_xADRecycleBin.help.txt
  DSCResources/MSFT_xADReplicationSite/en-US/about_xADReplicationSite.help.txt
  DSCResources/MSFT_xADReplicationSiteLink/en-US/about_xADReplicationSiteLink.help.txt
  DSCResources/MSFT_xADReplicationSubnet/en-US/about_xADReplicationSubnet.help.txt
  DSCResources/MSFT_xADServicePrincipalName/en-US/about_xADServicePrincipalName.help.txt
  DSCResources/MSFT_xADUser/en-US/about_xADUser.help.txt
  DSCResources/MSFT_xWaitForADDomain/en-US/about_xWaitForADDomain.help.txt
  Modules/xActiveDirectory.Common/en-US/xActiveDirectory.Common.strings.psd1
  Modules/xActiveDirectory.Common/xActiveDirectory.Common.psm1
  Tests/Integration/MSFT_xADDomainTrust.Integration.Tests.ps1
  Tests/Integration/MSFT_xADDomainTrust.config.ps1
  Tests/Unit/MSFT_xADDomainTrust.Tests.ps1
  Tests/Unit/xActiveDirectory.Common.Tests.ps1
Labels: needs review

#433 xActiveDirectory: Fix BOM in *.help.txt
  DSCResources/MSFT_xADComputer/en-US/about_xADComputer.help.txt
  DSCResources/MSFT_xADDomain/en-US/about_xADDomain.help.txt
  DSCResources/MSFT_xADDomainController/en-US/about_xADDomainController.help.txt
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/en-US/about_xADDomainDefaultPasswordPolicy.help.txt
  DSCResources/MSFT_xADDomainTrust/en-US/about_xADDomainTrust.help.txt
  DSCResources/MSFT_xADForestProperties/en-US/about_xADForestProperties.help.txt
  DSCResources/MSFT_xADGroup/en-US/about_xADGroup.help.txt
  DSCResources/MSFT_xADKDSKey/en-US/about_xADKDSKey.help.txt
  DSCResources/MSFT_xADManagedServiceAccount/en-US/about_xADManagedServiceAccount.help.txt
  DSCResources/MSFT_xADObjectEnabledState/en-US/about_xADObjectEnabledState.help.txt
  DSCResources/MSFT_xADObjectPermissionEntry/en-US/about_xADObjectPermissionEntry.help.txt
  DSCResources/MSFT_xADOrganizationalUnit/en-US/about_xADOrganizationalUnit.help.txt
  DSCResources/MSFT_xADRecycleBin/en-US/about_xADRecycleBin.help.txt
  DSCResources/MSFT_xADReplicationSite/en-US/about_xADReplicationSite.help.txt
  DSCResources/MSFT_xADReplicationSiteLink/en-US/about_xADReplicationSiteLink.help.txt
  DSCResources/MSFT_xADReplicationSubnet/en-US/about_xADReplicationSubnet.help.txt
  DSCResources/MSFT_xADServicePrincipalName/en-US/about_xADServicePrincipalName.help.txt
  DSCResources/MSFT_xADUser/en-US/about_xADUser.help.txt
  DSCResources/MSFT_xWaitForADDomain/en-US/about_xWaitForADDomain.help.txt
Labels: needs review

#435 xWaitForADDomain: Fix Issue #341
  CHANGELOG.md
  DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1
Labels: needs review

#406 xADDomainController: Add RODC Creation Support
  CHANGELOG.md
  DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1
  DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.schema.mof
  DSCResources/MSFT_xADDomainController/README.md
  DSCResources/MSFT_xADDomainController/en-US/MSFT_xADDomainController.strings.psd1
  DSCResources/MSFT_xADDomainController/en-US/about_xADDomainController.help.txt
  Examples/Resources/xADDomainController/4-AddReadOnlyDomainController_Config.ps1
  Tests/Unit/MSFT_xADDomainController.Tests.ps1
  Tests/Unit/Stubs/ActiveDirectoryStub.psm1
  Tests/Unit/Stubs/Microsoft.ActiveDirectory.Management.cs
Labels: waiting for code fix

#436 Remove PSAvoidUsingConvertToSecureStringWithPlainText
  CHANGELOG.md
  Tests/Unit/MSFT_xADComputer.Tests.ps1
  Tests/Unit/MSFT_xADDomain.Tests.ps1
  Tests/Unit/MSFT_xADDomainDefaultPasswordPolicy.Tests.ps1
  Tests/Unit/MSFT_xADDomainTrust.Tests.ps1
  Tests/Unit/MSFT_xADGroup.Tests.ps1
  Tests/Unit/MSFT_xADKDSKey.Tests.ps1
  Tests/Unit/MSFT_xADManagedServiceAccount.Tests.ps1
  Tests/Unit/MSFT_xADObjectEnabledState.Tests.ps1
  Tests/Unit/MSFT_xADOrganizationalUnit.Tests.ps1
  Tests/Unit/MSFT_xWaitForADDomain.Tests.ps1
Labels: needs review

#440 Fixes Issue #340 #339 #335 #330
  CHANGELOG.md
  DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1
  DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.psm1
  DSCResources/MSFT_xADRecycleBin/MSFT_xADRecycleBin.psm1
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
Labels: waiting for code fix

#441 xActiveDirectory: Removing SupportsShouldProcess
  CHANGELOG.md
  DSCResources/MSFT_xADObjectPermissionEntry/MSFT_xADObjectPermissionEntry.psm1
  DSCResources/MSFT_xADRecycleBin/MSFT_xADRecycleBin.psm1
  DSCResources/MSFT_xADRecycleBin/en-US/MSFT_xADRecycleBin.strings.psd1
  Tests/Unit/MSFT_xADOrganizationalUnit.Tests.ps1
Labels: needs review

#444 Add Comment Based Help to all xActiveDirectory.Common Functions - Fixes #321
  CHANGELOG.md
  DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
  Modules/xActiveDirectory.Common/xActiveDirectory.Common.psm1
Labels: needs review

#445 Update CHANGELOG.md
  CHANGELOG.md
Labels: needs review

#449 Update README.md
  README.md
Labels: ready for merge

#452 BREAKING CHANGE: ADUser: Renamed the parameter DomainAdministratorCredential
  CHANGELOG.md
  DSCResources/MSFT_ADUser/MSFT_ADUser.psm1
  DSCResources/MSFT_ADUser/MSFT_ADUser.schema.mof
  DSCResources/MSFT_ADUser/en-US/MSFT_ADUser.strings.psd1
  Examples/Resources/ADComputer/1-AddComputerAccount_Config.ps1
  Examples/Resources/ADComputer/2-AddComputerAccountDisabled_Config.ps1
  Examples/Resources/ADComputer/3-AddComputerAccountSpecificPath_Config.ps1
  Examples/Resources/ADComputer/4-AddComputerAccountAndCreateODJRequest_Config.ps1
  Examples/Resources/ADDomain/1-NewForest_Config.ps1
  Examples/Resources/ADDomain/2-NewChildDomain_Config.ps1
  Examples/Resources/ADDomain/3-NewForestwithParentAndChildDomain_Config.ps1
  Examples/Resources/ADDomain/4-NewDomainWithTwoDCs_Config.ps1
  Examples/Resources/ADDomainController/1-AddDomainControllerToDomainMinimal_Config.ps1
  Examples/Resources/ADDomainController/2-AddDomainControllerToDomainAllProperties_Config.ps1
  Examples/Resources/ADDomainController/3-AddDomainControllerToDomainUsingIFM_Config.ps1
  Examples/Resources/ADDomainDefaultPasswordPolicy/1-ConfigureDefaultPasswordPolicy_Config.ps1
  Examples/Resources/ADDomainTrust/1-NewOneWayTrust_Config.ps1
  Examples/Resources/ADForestProperties/1-ReplaceForestProperties_Config.ps1
  Examples/Resources/ADForestProperties/2-AddRemoveForestProperties_Config.ps1
  Examples/Resources/ADGroup/1-NewGroup_Config.ps1
  Examples/Resources/ADGroup/2-NewGroupWithMembers_Config.ps1
  Examples/Resources/ADGroup/3-NewGroupMultidomainMembers_Config.ps1
  Examples/Resources/ADKDSKey/1-CreateKDSRootKey_Config.ps1
  Examples/Resources/ADKDSKey/2-CreateKDSRootKeyInPast_Config.ps1
  Examples/Resources/ADKDSKey/3-CreateKDSRootKeyRemoveLastKey_Config.ps1
  Examples/Resources/ADManagedServiceAccount/1-CreateManagedServiceAccount_Config.ps1
  Examples/Resources/ADManagedServiceAccount/2-CreateGroupManagedServiceAccount_Config.ps1
  Examples/Resources/ADManagedServiceAccount/3-CreateGroupManagedServiceAccountWithMembers_Config.ps1
  Examples/Resources/ADObjectPermissionEntry/1-DelegateFullControl_Config.ps1
  Examples/Resources/ADObjectPermissionEntry/2-CreateDeleteComputerObject_Config.ps1
  Examples/Resources/ADObjectPermissionEntry/3-ReadWriteComputerObjectProperties_Config.ps1
  Examples/Resources/ADOrganizationalUnit/1-CreateADOU_Config.ps1
  Examples/Resources/ADRecycleBin/1-EnableADRecycleBin_Config.ps1
  Examples/Resources/ADReplicationSite/1-CreateADReplicationSite_Config.ps1
  Examples/Resources/ADReplicationSite/2-CreateADReplicationSiteRenameDefault_Config.ps1
  Examples/Resources/ADReplicationSite/3-RemoveADReplicationSite_Config.ps1
  Examples/Resources/ADReplicationSiteLInk/1-CreateReplicationSiteLink_Config.ps1
  Examples/Resources/ADReplicationSiteLInk/2-ModifyExistingReplicationSiteLink_Config.ps1
  Examples/Resources/ADReplicationSubnet/1-CreateReplicationSubnet_Config.ps1
  Examples/Resources/ADServicePrincipalName/1-AddUserServicePrincipalName_Config.ps1
  Examples/Resources/ADServicePrincipalName/2-AddComputerServicePrincipalName_Config.ps1
  Examples/Resources/ADUser/1-CreateUserAndManagePassword_Config.ps1
  Examples/Resources/ADUser/2-CreateUserAndIgnorePasswordChanges_Config.ps1
  Examples/Resources/WaitForADDomain/1-WaitForADDomain_Config.ps1
  Tests/Integration/MSFT_ADUser.Integration.Tests.ps1
  Tests/Integration/MSFT_ADUser.config.ps1
  Tests/Unit/MSFT_ADUser.Tests.ps1
Labels: breaking change, needs review

#453 BREAKING CHANGE: ADComputer: Remove obsolete Enabled parameter
  CHANGELOG.md
  DSCResources/MSFT_ADComputer/MSFT_ADComputer.psm1
  DSCResources/MSFT_ADComputer/MSFT_ADComputer.schema.mof
  DSCResources/MSFT_ADComputer/en-US/MSFT_ADComputer.strings.psd1
  DSCResources/MSFT_ADComputer/en-US/about_ADComputer.help.txt
  Tests/Unit/MSFT_ADComputer.Tests.ps1
Labels: breaking change, needs review

#454 BREAKING CHANGE: ActiveDirectory: Rename parameter DomainAdministratorCredential
  CHANGELOG.md
  DSCResources/MSFT_ADComputer/MSFT_ADComputer.psm1
  DSCResources/MSFT_ADComputer/MSFT_ADComputer.schema.mof
  DSCResources/MSFT_ADComputer/en-US/about_ADComputer.help.txt
  DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1
  DSCResources/MSFT_ADDomain/MSFT_ADDomain.schema.mof
  DSCResources/MSFT_ADDomain/en-US/about_ADDomain.help.txt
  DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.psm1
  DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.schema.mof
  DSCResources/MSFT_ADDomainController/README.md
  DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt
  DSCResources/MSFT_ADDomainDefaultPasswordPolicy/en-US/about_ADDomainDefaultPasswordPolicy.help.txt
  DSCResources/MSFT_ADDomainTrust/MSFT_ADDomainTrust.psm1
  DSCResources/MSFT_ADDomainTrust/MSFT_ADDomainTrust.schema.mof
  DSCResources/MSFT_ADDomainTrust/en-US/about_ADDomainTrust.help.txt
  DSCResources/MSFT_ADForestProperties/en-US/about_ADForestProperties.help.txt
  DSCResources/MSFT_ADGroup/en-US/about_ADGroup.help.txt
  DSCResources/MSFT_ADKDSKey/en-US/about_ADKDSKey.help.txt
  DSCResources/MSFT_ADManagedServiceAccount/en-US/about_ADManagedServiceAccount.help.txt
  DSCResources/MSFT_ADObjectEnabledState/en-US/about_ADObjectEnabledState.help.txt
  DSCResources/MSFT_ADObjectPermissionEntry/en-US/about_ADObjectPermissionEntry.help.txt
  DSCResources/MSFT_ADOrganizationalUnit/en-US/about_ADOrganizationalUnit.help.txt
  DSCResources/MSFT_ADRecycleBin/en-US/about_ADRecycleBin.help.txt
  DSCResources/MSFT_ADReplicationSite/en-US/about_ADReplicationSite.help.txt
  DSCResources/MSFT_ADReplicationSiteLink/en-US/about_ADReplicationSiteLink.help.txt
  DSCResources/MSFT_ADReplicationSubnet/en-US/about_ADReplicationSubnet.help.txt
  DSCResources/MSFT_ADServicePrincipalName/en-US/about_ADServicePrincipalName.help.txt
  DSCResources/MSFT_ADUser/en-US/about_ADUser.help.txt
  DSCResources/MSFT_WaitForADDomain/en-US/about_WaitForADDomain.help.txt
  Examples/Resources/ADComputer/1-ADComputer_AddComputerAccount_Config.ps1
  Examples/Resources/ADComputer/2-ADComputer_AddComputerAccountDisabled_Config.ps1
  Examples/Resources/ADComputer/3-ADComputer_AddComputerAccountSpecificPath_Config.ps1
  Examples/Resources/ADComputer/4-ADComputer_AddComputerAccountAndCreateODJRequest_Config.ps1
  Examples/Resources/ADDomain/1-ADDomain_NewForest_Config.ps1
  Examples/Resources/ADDomain/2-ADDomain_NewChildDomain_Config.ps1
  Examples/Resources/ADDomain/3-ADDomain_NewForestwithParentAndChildDomain_Config.ps1
  Examples/Resources/ADDomain/4-ADDomain_NewDomainWithTwoDCs_Config.ps1
  Examples/Resources/ADDomainController/1-ADDomainController_AddDomainControllerToDomainMinimal_Config.ps1
  Examples/Resources/ADDomainController/2-ADDomainController_AddDomainControllerToDomainAllProperties_Config.ps1
  Examples/Resources/ADDomainController/3-ADDomainController_AddDomainControllerToDomainUsingIFM_Config.ps1
  Examples/Resources/ADDomainController/4-ADDomainController_AddReadOnlyDomainController_Config.ps1
  Examples/Resources/ADDomainDefaultPasswordPolicy/1-ADDomainDefaultPasswordPolicy_ConfigureDefaultPasswordPolicy_Config.ps1
  Examples/Resources/ADDomainTrust/1-ADDomainTrust_NewOneWayTrust_Config.ps1
  Examples/Resources/ADForestProperties/1-ADForestProperties_ReplaceForestProperties_Config.ps1
  Examples/Resources/ADObjectEnabledState/2-ADObjectEnabledState_CreateClusterComputerAccount_Config.ps1
  Examples/Resources/ADObjectEnabledState/3-ADObjectEnabledState_EnabledPrestagedClusterComputerAccount_Config.ps1
  Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
  Tests/Integration/MSFT_ADComputer.Integration.Tests.ps1
  Tests/Integration/MSFT_ADDomainTrust.Integration.Tests.ps1
  Tests/Integration/MSFT_ADDomainTrust.config.ps1
  Tests/Integration/MSFT_ADUser.Integration.Tests.ps1
  Tests/Unit/ActiveDirectory.Common.Tests.ps1
  Tests/Unit/MSFT_ADComputer.Tests.ps1
  Tests/Unit/MSFT_ADDomain.Tests.ps1
  Tests/Unit/MSFT_ADDomainController.Tests.ps1
  Tests/Unit/MSFT_ADDomainTrust.Tests.ps1
Labels: breaking change
