Repository dsccommunity/ActiveDirectoryDsc, pull requests merged in 2019-06, with the labels that each got.

#304 xADReplicationSiteLink: Fix ADIdentityNotFoundException When Creating a New Site Link
  CHANGELOG.md
  DSCResources/MSFT_xADReplicationSiteLink/MSFT_xADReplicationSiteLink.psm1
  DSCResources/MSFT_xADReplicationSiteLink/en-US/MSFT_xADReplicationSiteLink.strings.psd1
  Tests/Unit/MSFT_xADReplicationSiteLink.tests.ps1
Labels: ready for merge

#303 xActiveDirectory: Fix Script Analyzer Rule Failures
  .MetaTestOptIn.json
  CHANGELOG.md
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/MSFT_xADDomainDefaultPasswordPolicy.psm1
  DSCResources/MSFT_xADDomainTrust/MSFT_xADDomainTrust.psm1
  DSCResources/MSFT_xADDomainTrust/en-US/MSFT_xADDomainTrust.strings.psd1
  DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.psm1
  DSCResources/MSFT_xADRecycleBin/MSFT_xADRecycleBin.psm1
  DSCResources/MSFT_xADRecycleBin/en-US/MSFT_xADRecycleBin.strings.psd1
  DSCResources/MSFT_xADReplicationSite/MSFT_xADReplicationSite.psm1
  DSCResources/MSFT_xADReplicationSite/en-US/MSFT_xADReplicationSite.strings.psd1
  DSCResources/MSFT_xADReplicationSubnet/MSFT_xADReplicationSubnet.psm1
  DSCResources/MSFT_xADReplicationSubnet/en-US/MSFT_xADReplicationSubnet.strings.psd1
  DSCResources/MSFT_xADServicePrincipalName/MSFT_xADServicePrincipalName.psm1
  DSCResources/MSFT_xADServicePrincipalName/en-US/MSFT_xADServicePrincipalName.strings.psd1
  DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1
  DSCResources/MSFT_xWaitForADDomain/en-US/MSFT_xWaitForADDomain.strings.psd1
  Tests/Unit/MSFT_xADRecycleBin.Tests.ps1
  Tests/Unit/MSFT_xADServicePrincipalName.Tests.ps1
Labels: waiting for code fix

#306 xActiveDirectory: Opt-In to DSC Resource Common Meta Tests
  .MetaTestOptIn.json
  CHANGELOG.md
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/MSFT_xADDomainDefaultPasswordPolicy.psm1
  DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1
  Examples/README.md
Labels: waiting for code fix

#308 xActiveDirectory: Fix RestoreFromRecycleBin description
  CHANGELOG.md
  DSCResources/MSFT_xADComputer/MSFT_xADComputer.schema.mof
  DSCResources/MSFT_xADGroup/MSFT_xADGroup.schema.mof
Labels: needs review

#307 xActiveDirectory: Opt-in to "Common Tests - Validate Localization" and standardise Localization files
  .MetaTestOptIn.json
  CHANGELOG.md
  DSCResources/MSFT_xADCommon/MSFT_xADCommon.psm1
  DSCResources/MSFT_xADCommon/en-US/MSFT_xADCommon.strings.psd1
  DSCResources/MSFT_xADComputer/en-US/MSFT_xADComputer.strings.psd1
  DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1
  DSCResources/MSFT_xADDomain/en-US/MSFT_xADDomain.strings.psd1
  DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1
  DSCResources/MSFT_xADDomainController/en-US/MSFT_xADDomainController.strings.psd1
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/MSFT_xADDomainDefaultPasswordPolicy.psm1
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/en-US/MSFT_xADDomainDefaultPasswordPolicy.strings.psd1
  DSCResources/MSFT_xADDomainTrust/en-US/MSFT_xADDomainTrust.strings.psd1
  DSCResources/MSFT_xADForestProperties/MSFT_xADForestProperties.psm1
  DSCResources/MSFT_xADForestProperties/en-US/MSFT_xADForestProperties.strings.psd1
  DSCResources/MSFT_xADForestProperties/en-us/MSFT_xADForestProperties.strings.psd1
  DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
  DSCResources/MSFT_xADGroup/en-US/MSFT_xADGroup.strings.psd1
  DSCResources/MSFT_xADKDSKey/MSFT_xADKDSKey.psm1
  DSCResources/MSFT_xADKDSKey/en-US/MSFT_xADKDSKey.strings.psd1
  DSCResources/MSFT_xADManagedServiceAccount/MSFT_xADManagedServiceAccount.psm1
  DSCResources/MSFT_xADManagedServiceAccount/en-US/MSFT_xADManagedServiceAccount.strings.psd1
  DSCResources/MSFT_xADObjectPermissionEntry/MSFT_xADObjectPermissionEntry.psm1
  DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.psm1
  DSCResources/MSFT_xADOrganizationalUnit/en-US/MSFT_xADOrganizationalUnit.strings.psd1
  DSCResources/MSFT_xADReplicationSiteLink/en-US/MSFT_xADReplicationSiteLink.strings.psd1
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
  DSCResources/MSFT_xADUser/en-US/MSFT_xADUser.strings.psd1
Labels: waiting for code fix

#310 xActiveDirectory: Move Resource Descriptions to Wiki
  CHANGELOG.md
  DSCResources/MSFT_xADComputer/README.md
  DSCResources/MSFT_xADDomain/README.md
  DSCResources/MSFT_xADDomainController/README.md
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/README.md
  DSCResources/MSFT_xADDomainTrust/README.md
  DSCResources/MSFT_xADForestProperties/README.md
  DSCResources/MSFT_xADGroup/README.md
  DSCResources/MSFT_xADKDSKey/README.md
  DSCResources/MSFT_xADManagedServiceAccount/README.md
  DSCResources/MSFT_xADObjectPermissionEntry/README.md
  DSCResources/MSFT_xADOrganizationalUnit/README.md
  DSCResources/MSFT_xADRecycleBin/README.md
  DSCResources/MSFT_xADReplicationSite/README.md
  DSCResources/MSFT_xADReplicationSiteLink/README.md
  DSCResources/MSFT_xADReplicationSubnet/README.md
  DSCResources/MSFT_xADServicePrincipalName/README.md
  DSCResources/MSFT_xADUser/README.md
  DSCResources/MSFT_xWaitForADDomain/README.md
  README.md
  appveyor.yml
Labels: needs review

#320 xActiveDirectory: Move MSFT_xADCommon helper functions
  CHANGELOG.md
  DSCResources/MSFT_xADCommon/MSFT_xADCommon.psm1
  DSCResources/MSFT_xADCommon/en-US/MSFT_xADCommon.strings.psd1
  DSCResources/MSFT_xADComputer/MSFT_xADComputer.psm1
  DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1
  DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/MSFT_xADDomainDefaultPasswordPolicy.psm1
  DSCResources/MSFT_xADForestProperties/MSFT_xADForestProperties.psm1
  DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
  DSCResources/MSFT_xADKDSKey/MSFT_xADKDSKey.psm1
  DSCResources/MSFT_xADManagedServiceAccount/MSFT_xADManagedServiceAccount.psm1
  DSCResources/MSFT_xADObjectPermissionEntry/MSFT_xADObjectPermissionEntry.psm1
  DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.psm1
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
  Modules/xActiveDirectory.Common/en-US/xActiveDirectory.Common.strings.psd1
  Modules/xActiveDirectory.Common/xActiveDirectory.Common.psm1
  Tests/Unit/MSFT_xADCommon.Tests.ps1
  Tests/Unit/MSFT_xADDomain.Tests.ps1
  Tests/Unit/MSFT_xADDomainDefaultPasswordPolicy.Tests.ps1
  Tests/Unit/MSFT_xADForestProperties.Tests.ps1
  Tests/Unit/MSFT_xADGroup.Tests.ps1
  Tests/Unit/MSFT_xADKDSKey.Tests.ps1
  Tests/Unit/MSFT_xADManagedServiceAccount.Tests.ps1
  Tests/Unit/MSFT_xADObjectPermissionEntry.Tests.ps1
  Tests/Unit/MSFT_xADOrganizationalUnit.Tests.ps1
  Tests/Unit/MSFT_xADRecycleBin.Tests.ps1
  Tests/Unit/MSFT_xADReplicationSite.Tests.ps1
  Tests/Unit/MSFT_xADReplicationSiteLink.tests.ps1
  Tests/Unit/MSFT_xADReplicationSubnet.Tests.ps1
  Tests/Unit/MSFT_xADServicePrincipalName.Tests.ps1
  Tests/Unit/MSFT_xADUser.Tests.ps1
  Tests/Unit/MSFT_xWaitForADDomain.Tests.ps1
  Tests/Unit/xActiveDirectory.Common.Tests.ps1
Labels: needs review

#362 xActiveDirectory: Deleted xActiveDirectory_TechNetDocumentation.html
  CHANGELOG.md
  xActiveDirectory_TechNetDocumentation.html
Labels: needs review

#313 Fix for issue 295
  CHANGELOG.md
  DSCResources/MSFT_xADComputer/MSFT_xADComputer.psm1
Labels: needs review

#363 xActiveDirectory: Fix Module Name reference in README
  README.md
Labels: ready for merge

#365 xADDomainTrust: Replace New-TerminatingError with Standard Function
  CHANGELOG.md
  DSCResources/MSFT_xADDomainTrust/MSFT_xADDomainTrust.psm1
Labels: needs review

#366 xADRecycleBin: Deleted Unneeded Example and Resource Designer files
  CHANGELOG.md
  DSCResources/MSFT_xADRecycleBin/Examples/xActiveDirectory_xADRecycleBin.ps1
  DSCResources/MSFT_xADRecycleBin/ResourceDesignerScripts/GeneratexADRecycleBinSchema.ps1
Labels: needs review

#372 xActiveDirectory: Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs review

#371 xADUser: Add ChangePasswordAtLogon Parameter
  CHANGELOG.md
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
  DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof
  DSCResources/MSFT_xADUser/en-US/MSFT_xADUser.strings.psd1
  Tests/Unit/MSFT_xADUser.Tests.ps1
Labels: ready for merge

#277 xADObjectEnabledState: New resource
  CHANGELOG.md
  DSCResources/MSFT_xADComputer/MSFT_xADComputer.psm1
  DSCResources/MSFT_xADObjectEnabledState/MSFT_xADObjectEnabledState.psm1
  DSCResources/MSFT_xADObjectEnabledState/MSFT_xADObjectEnabledState.schema.mof
  DSCResources/MSFT_xADObjectEnabledState/README.md
  DSCResources/MSFT_xADObjectEnabledState/en-US/MSFT_xADObjectEnabledState.strings.psd1
  Examples/Resources/xADObjectEnabledState/1-EnabledComputerAccount_Config.ps1
  Examples/Resources/xADObjectEnabledState/2-CreateClusterComputerAccount_Config.ps1
  Examples/Resources/xADObjectEnabledState/3-EnabledPrestagedClusterComputerAccount_Config.ps1
  Modules/xActiveDirectory.Common/xActiveDirectory.Common.psm1
  Tests/Integration/MSFT_xADComputer.Integration.Tests.ps1
  Tests/Integration/MSFT_xADObjectEnableState.Integration.Tests.ps1
  Tests/Integration/MSFT_xADObjectEnabledState.config.ps1
  Tests/Unit/MSFT_xADObjectEnabledState.Tests.ps1
Labels: ready for merge

#370 xActiveDirectory: Add Missing and Fix Wiki Corruption Causing Schema Descriptions
  CHANGELOG.md
  DSCResources/MSFT_xADRecycleBin/MSFT_xADRecycleBin.schema.mof
  DSCResources/MSFT_xADReplicationSubnet/MSFT_xADReplicationSubnet.schema.mof
  DSCResources/MSFT_xADServicePrincipalName/MSFT_xADServicePrincipalName.schema.mof
  DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.schema.mof
Labels: needs review

#326 xActiveDirectory: Cleanup code
  CHANGELOG.md
  DSCResources/MSFT_xADComputer/MSFT_xADComputer.psm1
  DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1
  DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/MSFT_xADDomainDefaultPasswordPolicy.psm1
  DSCResources/MSFT_xADDomainTrust/MSFT_xADDomainTrust.psm1
  DSCResources/MSFT_xADForestProperties/MSFT_xADForestProperties.psm1
  DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
  DSCResources/MSFT_xADKDSKey/MSFT_xADKDSKey.psm1
  DSCResources/MSFT_xADManagedServiceAccount/MSFT_xADManagedServiceAccount.psm1
  DSCResources/MSFT_xADObjectPermissionEntry/MSFT_xADObjectPermissionEntry.psm1
  DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.psm1
  DSCResources/MSFT_xADRecycleBin/MSFT_xADRecycleBin.psm1
  DSCResources/MSFT_xADRecycleBin/en-US/MSFT_xADRecycleBin.strings.psd1
  DSCResources/MSFT_xADReplicationSiteLink/MSFT_xADReplicationSiteLink.psm1
  DSCResources/MSFT_xADReplicationSubnet/MSFT_xADReplicationSubnet.psm1
  DSCResources/MSFT_xADServicePrincipalName/MSFT_xADServicePrincipalName.psm1
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
  DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1
  Modules/xActiveDirectory.Common/xActiveDirectory.Common.psm1
  Tests/Unit/MSFT_xADDomain.Tests.ps1
  Tests/Unit/MSFT_xADDomainDefaultPasswordPolicy.Tests.ps1
  Tests/Unit/MSFT_xADGroup.Tests.ps1
  Tests/Unit/MSFT_xADKDSKey.Tests.ps1
  Tests/Unit/MSFT_xADManagedServiceAccount.Tests.ps1
  Tests/Unit/MSFT_xADObjectPermissionEntry.Tests.ps1
  Tests/Unit/MSFT_xADOrganizationalUnit.Tests.ps1
  Tests/Unit/MSFT_xADRecycleBin.Tests.ps1
  Tests/Unit/MSFT_xADReplicationSite.Tests.ps1
  Tests/Unit/MSFT_xADReplicationSubnet.Tests.ps1
  Tests/Unit/MSFT_xADServicePrincipalName.Tests.ps1
  Tests/Unit/MSFT_xADUser.Tests.ps1
  Tests/Unit/MSFT_xWaitForADDomain.Tests.ps1
  Tests/Unit/xActiveDirectory.Common.Tests.ps1
Labels: ready for merge

#376 xADUser: Add pwdLastSet ADProperty to ChangePasswordAtLogon
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
Labels: needs review

#373 xADUser: Add Additional Parameters
  CHANGELOG.md
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
  DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof
  Tests/Unit/MSFT_xADUser.Tests.ps1
Labels: needs review

#378 xADObjectEnabledState: Update comment-based help
  DSCResources/MSFT_xADObjectEnabledState/MSFT_xADObjectEnabledState.psm1
Labels: needs review

#380 xADComputer: Removes helper function Set-DscADComputer
  DSCResources/MSFT_xADComputer/MSFT_xADComputer.psm1
Labels: needs review

#381 xActiveDirectory: Remove Unused Legacy Test Files
  Assert-HADC.ps1
  Assert-ParentChildDomains.ps1
  CHANGELOG.md
  HADCConfiguration.psd1
  ParentChildConfig.psd1
Labels: needs review

#379 xADUser: Add ProxyAddresses Property
  CHANGELOG.md
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
  DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof
  DSCResources/MSFT_xADUser/en-US/MSFT_xADUser.strings.psd1
  Tests/Unit/MSFT_xADUser.Tests.ps1
Labels: needs review

#385 xActiveDirectory: Use fully qualified type names
  CHANGELOG.md
  DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1
  DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1
  DSCResources/MSFT_xADDomainTrust/MSFT_xADDomainTrust.psm1
  DSCResources/MSFT_xADForestProperties/MSFT_xADForestProperties.psm1
  DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1
  DSCResources/MSFT_xADManagedServiceAccount/MSFT_xADManagedServiceAccount.psm1
  DSCResources/MSFT_xADObjectPermissionEntry/MSFT_xADObjectPermissionEntry.psm1
  DSCResources/MSFT_xADReplicationSiteLink/MSFT_xADReplicationSiteLink.psm1
  DSCResources/MSFT_xADReplicationSubnet/MSFT_xADReplicationSubnet.psm1
  DSCResources/MSFT_xADServicePrincipalName/MSFT_xADServicePrincipalName.psm1
  DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1
  Examples/Resources/xADDomain/1-NewForest_Config.ps1
  Examples/Resources/xADDomain/2-NewChildDomain_Config.ps1
  Examples/Resources/xADDomain/3-NewForestwithParentAndChildDomain_Config.ps1
  Examples/Resources/xADDomain/4-NewDomainWithTwoDCs_Config.ps1
  Examples/Resources/xADDomainDefaultPasswordPolicy/1-ConfigureDefaultPasswordPolicy_Config.ps1
  Examples/Resources/xADDomainTrust/1-NewOneWayTrust_Config.ps1
  Examples/Resources/xADForestProperties/1-ReplaceForestProperties_Config.ps1
  Examples/Resources/xADForestProperties/2-AddRemoveForestProperties_Config.ps1
  Examples/Resources/xADGroup/1-NewGroup_Config.ps1
  Examples/Resources/xADGroup/2-NewGroupWithMembers_Config.ps1
  Examples/Resources/xADGroup/3-NewGroupMultidomainMembers_Config.ps1
  Examples/Resources/xADKDSKey/1-CreateKDSRootKey_Config.ps1
  Examples/Resources/xADKDSKey/2-CreateKDSRootKeyInPast_Config.ps1
  Examples/Resources/xADKDSKey/3-CreateKDSRootKeyRemoveLastKey_Config.ps1
  Examples/Resources/xADManagedServiceAccount/1-CreateManagedServiceAccount_Config.ps1
  Examples/Resources/xADManagedServiceAccount/2-CreateGroupManagedServiceAccount_Config.ps1
  Examples/Resources/xADManagedServiceAccount/3-CreateGroupManagedServiceAccountWithMembers_Config.ps1
  Examples/Resources/xADObjectPermissionEntry/1-DelegateFullControl_Config.ps1
  Examples/Resources/xADObjectPermissionEntry/2-CreateDeleteComputerObject_Config.ps1
  Examples/Resources/xADObjectPermissionEntry/3-ReadWriteComputerObjectProperties_Config.ps1
  Examples/Resources/xADOrganizationalUnit/1-CreateADOU_Config.ps1
  Examples/Resources/xADRecycleBin/1-EnableADRecycleBin_Config.ps1
  Examples/Resources/xADReplicationSite/1-CreateADReplicationSite_Config.ps1
  Examples/Resources/xADReplicationSite/2-CreateADReplicationSiteRenameDefault_Config.ps1
  Examples/Resources/xADReplicationSite/3-RemoveADReplicationSite_Config.ps1
  Examples/Resources/xADReplicationSiteLInk/1-CreateReplicationSiteLink_Config.ps1
  Examples/Resources/xADReplicationSiteLInk/2-ModifyExistingReplicationSiteLink_Config.ps1
  Examples/Resources/xADUser/1-CreateUserAndManagePassword_Config.ps1
  Examples/Resources/xADUser/2-CreateUserAndIgnorePasswordChanges_Config.ps1
  Modules/xActiveDirectory.Common/xActiveDirectory.Common.psm1
  Tests/Integration/MSFT_xADComputer.Integration.Tests.ps1
  Tests/Integration/MSFT_xADObjectEnableState.Integration.Tests.ps1
  Tests/Unit/MSFT_xADDomain.Tests.ps1
  Tests/Unit/MSFT_xADGroup.Tests.ps1
  Tests/Unit/MSFT_xADKDSKey.Tests.ps1
  Tests/Unit/MSFT_xADManagedServiceAccount.Tests.ps1
  Tests/Unit/MSFT_xADOrganizationalUnit.Tests.ps1
  Tests/Unit/xActiveDirectory.Common.Tests.ps1
Labels: needs review

#386 xActiveDirectory: Add Resource Descriptions
  DSCResources/MSFT_xADComputer/README.md
  DSCResources/MSFT_xADDomainTrust/README.md
  DSCResources/MSFT_xADKDSKey/README.md
  DSCResources/MSFT_xADManagedServiceAccount/README.md
  DSCResources/MSFT_xADOrganizationalUnit/README.md
  DSCResources/MSFT_xADReplicationSite/README.md
  DSCResources/MSFT_xADReplicationSiteLink/README.md
  DSCResources/MSFT_xADServicePrincipalName/README.md
  DSCResources/MSFT_xADUser/README.md
  DSCResources/MSFT_xWaitForADDomain/README.md
Labels: needs review

#388 xADComputer: Fix ServicePrincipalNames Empty String Exception
  CHANGELOG.md
  DSCResources/MSFT_xADComputer/MSFT_xADComputer.psm1
  Tests/Unit/MSFT_xADComputer.Tests.ps1
Labels: needs review

#389 xADUser: Fix Password Property Being Updated Whenever Another Property is Changed
  CHANGELOG.md
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
  Tests/Unit/MSFT_xADUser.Tests.ps1
Labels: ready for merge

#391 xActiveDirectory: Update Example List README with missing Resources
  CHANGELOG.md
  Examples/README.md
Labels: needs review

#392 xADUser: Replace Write-Error with the correct helper function
  CHANGELOG.md
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
  Tests/Unit/MSFT_xADUser.Tests.ps1
Labels: ready for merge

#393 xADRecycleBin: Replace Write-Error with the correct helper function
  CHANGELOG.md
  DSCResources/MSFT_xADRecycleBin/MSFT_xADRecycleBin.psm1
  Tests/Unit/MSFT_xADRecycleBin.Tests.ps1
Labels: ready for merge

#396 xADOrganizationalUnit: Verbose Message Fix
  CHANGELOG.md
  DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.psm1
  DSCResources/MSFT_xADOrganizationalUnit/en-US/MSFT_xADOrganizationalUnit.strings.psd1
Labels: needs review

#397 xActiveDirectory: Add Missing Resource Examples
  CHANGELOG.md
  Examples/README.md
  Examples/Resources/xADReplicationSubnet/1-CreateReplicationSubnet_Config.ps1
  Examples/Resources/xADServicePrincipalName/1-AddUserServicePrincipalName_Config.ps1
  Examples/Resources/xADServicePrincipalName/2-AddComputerServicePrincipalName_Config.ps1
  Examples/Resources/xWaitForADDomain/1-WaitForADDomain_Config.ps1
Labels: ready for merge

#399 xActiveDirectory: Requirements section
  CHANGELOG.md
  DSCResources/MSFT_xADDomain/README.md
  DSCResources/MSFT_xADDomainController/README.md
  DSCResources/MSFT_xADDomainDefaultPasswordPolicy/README.md
  DSCResources/MSFT_xADDomainTrust/README.md
  DSCResources/MSFT_xADForestProperties/README.md
  DSCResources/MSFT_xADGroup/README.md
  DSCResources/MSFT_xADKDSKey/README.md
  DSCResources/MSFT_xADManagedServiceAccount/README.md
  DSCResources/MSFT_xADObjectPermissionEntry/README.md
  DSCResources/MSFT_xADOrganizationalUnit/README.md
  DSCResources/MSFT_xADRecycleBin/README.md
  DSCResources/MSFT_xADReplicationSite/README.md
  DSCResources/MSFT_xADReplicationSiteLink/README.md
  DSCResources/MSFT_xADReplicationSubnet/README.md
  DSCResources/MSFT_xADServicePrincipalName/README.md
  DSCResources/MSFT_xADUser/README.md
  DSCResources/MSFT_xWaitForADDomain/README.md
Labels: waiting for code fix

#403 Update CHANGELOG.md
  CHANGELOG.md
Labels: ready for merge
