Repository dsccommunity/ActiveDirectoryDsc, pull requests merged in 2019-05, with the labels that each got.

#255 xADDomainController: Added new parameter IsGlobalCatalog
  CHANGELOG.md
  DSCResources/MSFT_xADCommon/MSFT_xADCommon.psm1
  DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1
  DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.schema.mof
  DSCResources/MSFT_xADDomainController/en-US/MSFT_xADDomainController.strings.psd1
  Examples/Resources/xADDomainController/1-AddDomainControllerToDomainMinimal.ps1
  Examples/Resources/xADDomainController/2-AddDomainControllerToDomainAllProperties.ps1
  Examples/Resources/xADDomainController/3-AddDomainControllerToDomainUsingIFM.ps1
  README.md
  Tests/Unit/MSFT_xADCommon.Tests.ps1
  Tests/Unit/MSFT_xADDomainController.Tests.ps1
Labels: needs review

#261 xADManagedServiceAccount: Fixed a few styling issues
  DSCResources/MSFT_xADManagedServiceAccount/MSFT_xADManagedServiceAccount.psm1
  DSCResources/MSFT_xADManagedServiceAccount/MSFT_xADManagedServiceAccount.schema.mof
  DSCResources/MSFT_xADManagedServiceAccount/en-US/MSFT_xADManagedServiceAccount.strings.psd1
  README.md
  Tests/Unit/MSFT_xADManagedServiceAccount.Tests.ps1
Labels: ready for merge

#266 Removing the Misc folder
  CHANGELOG.md
  Misc/New-ADDomainTrust.ps1
Labels: waiting for code fix

#270 xActiveDirectory: Combine DscResource.LocalizationHelper and DscResource.Common
  CHANGELOG.md
  DSCResources/MSFT_xADCommon/MSFT_xADCommon.psm1
  DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1
  DSCResources/MSFT_xADKDSKey/MSFT_xADKDSKey.psm1
  DSCResources/MSFT_xADManagedServiceAccount/MSFT_xADManagedServiceAccount.psm1
  DSCResources/MSFT_xADReplicationSiteLink/MSFT_xADReplicationSiteLink.psm1
  Modules/DscResource.Common/DscResource.Common.psm1
  Modules/DscResource.LocalizationHelper/DscResource.LocalizationHelper.psm1
  Modules/xActiveDirectory.Common/en-US/xActiveDirectory.Common.strings.psd1
  Modules/xActiveDirectory.Common/xActiveDirectory.Common.psm1
  Tests/Unit/DscResource.LocalizationHelper.Tests.ps1
  Tests/Unit/xActiveDirectory.Common.Tests.ps1
Labels: needs review

#272 xActiveDirectory: Restoring an object no longer fails
  CHANGELOG.md
  DSCResources/MSFT_xADCommon/MSFT_xADCommon.psm1
  Tests/Unit/MSFT_xADCommon.Tests.ps1
Labels: needs review

#170 BREAKING CHANGE: xADComputer: A computer account can now be created disabled
  CHANGELOG.md
  DSCResources/MSFT_xADCommon/MSFT_xADCommon.psm1
  DSCResources/MSFT_xADComputer/MSFT_xADComputer.psm1
  DSCResources/MSFT_xADComputer/MSFT_xADComputer.schema.mof
  DSCResources/MSFT_xADComputer/en-US/MSFT_xADComputer.psd1
  DSCResources/MSFT_xADComputer/en-US/MSFT_xADComputer.strings.psd1
  DSCResources/MSFT_xADGroup/MSFT_xADGroup.schema.mof
  DSCResources/MSFT_xADObjectPermissionEntry/MSFT_xADObjectPermissionEntry.schema.mof
  DSCResources/MSFT_xADOrganizationalUnit/MSFT_xADOrganizationalUnit.schema.mof
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
  DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof
  Examples/README.md
  Examples/Resources/xADComputer/1-AddComputerAccount_Config.ps1
  Examples/Resources/xADComputer/2-AddComputerAccountDisabled_Config.ps1
  Examples/Resources/xADComputer/3-AddComputerAccountSpecificPath_Config.ps1
  Examples/Resources/xADComputer/4-AddComputerAccountAndCreateODJRequest_Config.ps1
  Examples/Resources/xADDomainController/1-AddDomainControllerToDomainMinimal.ps1
  Examples/Resources/xADDomainController/2-AddDomainControllerToDomainAllProperties.ps1
  Examples/Resources/xADDomainController/3-AddDomainControllerToDomainUsingIFM.ps1
  Modules/xActiveDirectory.Common/en-US/xActiveDirectory.Common.strings.psd1
  Modules/xActiveDirectory.Common/xActiveDirectory.Common.psm1
  README.md
  Tests/Integration/MSFT_xADComputer.Integration.Tests.ps1
  Tests/Integration/MSFT_xADComputer.config.ps1
  Tests/Unit/MSFT_xADCommon.Tests.ps1
  Tests/Unit/MSFT_xADComputer.Tests.ps1
  Tests/Unit/xActiveDirectory.Common.Tests.ps1
Labels: breaking change, needs review

#290 Update CHANGELOG.md
  CHANGELOG.md
Labels: needs review

#274 xADUser: Adding ServicePrincipalNames property
  CHANGELOG.md
  DSCResources/MSFT_xADUser/MSFT_xADUser.psm1
  DSCResources/MSFT_xADUser/MSFT_xADUser.schema.mof
  README.md
  Tests/Unit/MSFT_xADUser.Tests.ps1
Labels: needs review

#285 xActiveDirectory: Suppressing Script Analyzer rule PSAvoidGlobalVars
  CHANGELOG.md
  DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1
  DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1
  DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1
Labels: needs review

#278 xActiveDirectory: Move the examples in the README.md to Examples folder
  CHANGELOG.md
  DSCResources/MSFT_xADDomain/MSFT_xADDomain.schema.mof
  Examples/Resources/xADDomain/3-NewForestwithParentAndChildDomain.ps1
  Examples/Resources/xADDomain/4-NewDomainWithTwoDCs.ps1
  Examples/Resources/xADDomainDefaultPasswordPolicy/1-ConfigureDefaultPasswordPolicy.ps1
  Examples/Resources/xADDomainTrust/1-NewOneWayTrust.ps1
  Examples/Resources/xADForestProperties/1-ReplaceForestProperties.ps1
  Examples/Resources/xADGroup/1-NewGroup.ps1
  Examples/Resources/xADOrganizationalUnit/1-CreateADOU.ps1
  Examples/Resources/xADRecycleBin/1-EnableADRecycleBin.ps1
  Examples/Resources/xADReplicationSite/1-CreateADReplicationSite.ps1
  Examples/Resources/xADReplicationSite/2-CreateADReplicationSiteRenameDefault.ps1
  Examples/Resources/xADReplicationSite/3-RemoveADReplicationSite.ps1
  README.md
Labels: needs review

#299 xADObjectPermissionEntry: Fix failure when applied in the same configuration as xADDomain
  CHANGELOG.md
  DSCResources/MSFT_xADCommon/MSFT_xADCommon.psm1
  DSCResources/MSFT_xADObjectPermissionEntry/MSFT_xADObjectPermissionEntry.psm1
  DSCResources/MSFT_xADObjectPermissionEntry/en-US/MSFT_xADObjectPermissionEntry.strings.psd1
  Tests/Unit/MSFT_xADCommon.Tests.ps1
  Tests/Unit/MSFT_xADObjectPermissionEntry.Tests.ps1
Labels: needs review
