Repository dsccommunity/ActiveDirectoryDsc, pull requests merged in 2019-08, with the labels that each got.

#455 BREAKING CHANGE: WaitForADDomain: Refactored the resource to handle timeout better
  ActiveDirectoryDsc.psd1
  CHANGELOG.md
  DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt
  DSCResources/MSFT_ADForestProperties/en-US/about_ADForestProperties.help.txt
  DSCResources/MSFT_ADKDSKey/MSFT_ADKDSKey.psm1
  DSCResources/MSFT_WaitForADDomain/MSFT_WaitForADDomain.psm1
  DSCResources/MSFT_WaitForADDomain/MSFT_WaitForADDomain.schema.mof
  DSCResources/MSFT_WaitForADDomain/README.md
  DSCResources/MSFT_WaitForADDomain/en-US/MSFT_WaitForADDomain.strings.psd1
  DSCResources/MSFT_WaitForADDomain/en-US/about_WaitForADDomain.help.txt
  Examples/Resources/ADDomainController/1-ADDomainController_AddDomainControllerToDomainMinimal_Config.ps1
  Examples/Resources/ADDomainController/2-ADDomainController_AddDomainControllerToDomainAllProperties_Config.ps1
  Examples/Resources/ADDomainController/3-ADDomainController_AddDomainControllerToDomainUsingIFM_Config.ps1
  Examples/Resources/ADDomainController/4-ADDomainController_AddReadOnlyDomainController_Config.ps1
  Examples/Resources/WaitForADDomain/1-WaitForADDomain_WaitForDomainController_Config.ps1
  Examples/Resources/WaitForADDomain/2-WaitForADDomain_WaitForDomainControllerUsingBuiltInCredential_Config.ps1
  Examples/Resources/WaitForADDomain/3-WaitForADDomain_WaitForDomainControllerUsingCredential_Config.ps1
  Examples/Resources/WaitForADDomain/4-WaitForADDomain_WaitForDomainControllerInSite_Config.ps1
  Examples/Resources/WaitForADDomain/5-WaitForADDomain_WaitForDomainControllerWithReboot_Config.ps1
  Examples/Resources/WaitForADDomain/6-WaitForADDomain_WaitForDomainControllerWithLongerDelay_Config.ps1
  Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
  Modules/ActiveDirectoryDsc.Common/en-US/ActiveDirectoryDsc.Common.strings.psd1
  Tests/Integration/MSFT_ADComputer.config.ps1
  Tests/Integration/MSFT_ADDomainTrust.config.ps1
  Tests/Integration/MSFT_ADObjectEnabledState.config.ps1
  Tests/Integration/MSFT_ADUser.config.ps1
  Tests/Integration/MSFT_WaitForADDomain.Integration.Tests.ps1
  Tests/Integration/MSFT_WaitForADDomain.config.ps1
  Tests/Unit/ActiveDirectory.Common.Tests.ps1
  Tests/Unit/MSFT_WaitForADDomain.Tests.ps1
Labels: breaking change

#460 ADUser: Update the default value logic for CommonName
  CHANGELOG.md
  DSCResources/MSFT_ADUser/MSFT_ADUser.psm1
Labels: needs review

#459 ActiveDirectoryDsc: Integration tests correctly evaluates Test-DscConfiguration
  CHANGELOG.md
  Tests/Integration/MSFT_ADComputer.Integration.Tests.ps1
  Tests/Integration/MSFT_ADDomainTrust.Integration.Tests.ps1
  Tests/Integration/MSFT_ADUser.Integration.Tests.ps1
Labels: needs review

#458 ADUser: Uses helper function Add-TypeAssembly
  CHANGELOG.md
  DSCResources/MSFT_ADUser/MSFT_ADUser.psm1
Labels: needs review

#465 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for merge

#464 ActiveDirectoryDsc: Fix comment based help
  CHANGELOG.md
  DSCResources/MSFT_ADComputer/MSFT_ADComputer.psm1
  DSCResources/MSFT_ADDomainDefaultPasswordPolicy/MSFT_ADDomainDefaultPasswordPolicy.psm1
  DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1
  DSCResources/MSFT_ADGroup/MSFT_ADGroup.schema.mof
  DSCResources/MSFT_ADGroup/en-US/about_ADGroup.help.txt
Labels: needs review

#457 BREAKING CHANGE: ADDomain: Add new parameter AllowTrustRecreation
  CHANGELOG.md
  DSCResources/MSFT_ADDomainTrust/MSFT_ADDomainTrust.psm1
  DSCResources/MSFT_ADDomainTrust/MSFT_ADDomainTrust.schema.mof
  DSCResources/MSFT_ADDomainTrust/en-US/MSFT_ADDomainTrust.strings.psd1
  DSCResources/MSFT_ADDomainTrust/en-US/about_ADDomainTrust.help.txt
  Examples/Resources/ADDomainTrust/1-ADDomainTrust_ExternalInboundTrust_Config.ps1
  Examples/Resources/ADDomainTrust/2-ADDomainTrust_ExternalInboundTrustWithOptInToRecreate_Config.ps1
  Tests/Unit/MSFT_ADDomainTrust.Tests.ps1
Labels: breaking change, needs review

#462 BREAKING CHANGE: xADRecycleBin refactor into xADOptionalFeature
  CHANGELOG.md
  DSCResources/MSFT_ADOptionalFeature/MSFT_ADOptionalFeature.psm1
  DSCResources/MSFT_ADOptionalFeature/MSFT_ADOptionalFeature.schema.mof
  DSCResources/MSFT_ADOptionalFeature/README.md
  DSCResources/MSFT_ADOptionalFeature/en-US/MSFT_ADOptionalFeature.strings.psd1
  DSCResources/MSFT_ADOptionalFeature/en-US/about_ADOptionalFeature.help.txt
  DSCResources/MSFT_ADRecycleBin/MSFT_ADRecycleBin.schema.mof
  DSCResources/MSFT_ADRecycleBin/README.md
  DSCResources/MSFT_ADRecycleBin/en-US/MSFT_ADRecycleBin.strings.psd1
  Examples/README.md
  Examples/Resources/ADOptionalFeature/1-ADOptionalFeature_EnableADRecycleBin_Config.ps1
  Tests/Integration/MSFT_ADOptionalFeature.Integration.Tests.ps1
  Tests/Integration/MSFT_ADOptionalFeature.config.ps1
  Tests/Unit/MSFT_ADOptionalFeature.Tests.ps1
  Tests/Unit/MSFT_ADRecycleBin.Tests.ps1
Labels: breaking change, needs review

#470 ActiveDIrectoryDsc: Updated to optimize module auto-discovery
  ActiveDirectoryDsc.psd1
  CHANGELOG.md
Labels: needs review

#468 ADUser: Add property ThumbnailPhoto
  .gitattributes
  CHANGELOG.md
  DSCResources/MSFT_ADUser/MSFT_ADUser.psm1
  DSCResources/MSFT_ADUser/MSFT_ADUser.schema.mof
  DSCResources/MSFT_ADUser/en-US/MSFT_ADUser.strings.psd1
  DSCResources/MSFT_ADUser/en-US/about_ADUser.help.txt
  Examples/Resources/ADUser/3-ADUser_UpdateThumbnailPhotoAsBase64_Config.ps1
  Examples/Resources/ADUser/4-ADUser_UpdateThumbnailPhotoFromFile_Config.ps1
  Examples/Resources/ADUser/5-ADUser_RemoveThumbnailPhoto_Config.ps1
  Tests/Integration/MSFT_ADUser.Integration.Tests.ps1
  Tests/Integration/MSFT_ADUser.config.ps1
  Tests/TestHelpers/DSC_Logo_96.jpg
  Tests/Unit/MSFT_ADUser.Tests.ps1
Labels: ready for merge

#469 ActiveDirectoryDsc: Update usage of $PSBoundParameters.Remove()
  CHANGELOG.md
  DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1
  DSCResources/MSFT_ADManagedServiceAccount/MSFT_ADManagedServiceAccount.psm1
Labels: needs review

#471 ActiveDirectoryDsc.Common: Refactor Remove-DuplicateMembers
  CHANGELOG.md
  Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
  Modules/ActiveDirectoryDsc.Common/en-US/ActiveDirectoryDsc.Common.strings.psd1
  Tests/Unit/ActiveDirectory.Common.Tests.ps1
Labels: needs review

#472 ADDomainController: Added new parameter FlexibleSingleMasterOperationRole
  CHANGELOG.md
  DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.psm1
  DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.schema.mof
  DSCResources/MSFT_ADDomainController/README.md
  DSCResources/MSFT_ADDomainController/en-US/MSFT_ADDomainController.strings.psd1
  DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt
  DSCResources/MSFT_ADOptionalFeature/en-US/about_ADOptionalFeature.help.txt
  Examples/Resources/ADDomainController/5-ADDomainController_AddDomainControllerAndMoveRole_Config.ps1
  Tests/Unit/MSFT_ADDomainController.Tests.ps1
  Tests/Unit/Stubs/ActiveDirectoryStub.psm1
  Tests/Unit/Stubs/Microsoft.ActiveDirectory.Management.cs
Labels: ready for merge

#473 ActiveDirectoryDsc: Update all tests to use BeTrue and BeFalse
  CHANGELOG.md
  Tests/Unit/ActiveDirectory.Common.Tests.ps1
  Tests/Unit/MSFT_ADDomain.Tests.ps1
  Tests/Unit/MSFT_ADDomainController.Tests.ps1
  Tests/Unit/MSFT_ADDomainDefaultPasswordPolicy.Tests.ps1
  Tests/Unit/MSFT_ADForestProperties.Tests.ps1
  Tests/Unit/MSFT_ADGroup.Tests.ps1
  Tests/Unit/MSFT_ADKDSKey.Tests.ps1
  Tests/Unit/MSFT_ADManagedServiceAccount.Tests.ps1
  Tests/Unit/MSFT_ADObjectPermissionEntry.Tests.ps1
  Tests/Unit/MSFT_ADOptionalFeature.Tests.ps1
  Tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1
  Tests/Unit/MSFT_ADReplicationSite.Tests.ps1
  Tests/Unit/MSFT_ADReplicationSiteLink.tests.ps1
  Tests/Unit/MSFT_ADReplicationSubnet.Tests.ps1
  Tests/Unit/MSFT_ADServicePrincipalName.Tests.ps1
  Tests/Unit/MSFT_ADUser.Tests.ps1
  Tests/Unit/MSFT_WaitForADDomain.Tests.ps1
Labels: needs review

#474 ADDomainControllerProperties: New resource
  CHANGELOG.md
  DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt
  DSCResources/MSFT_ADDomainControllerProperties/MSFT_ADDomainControllerProperties.psm1
  DSCResources/MSFT_ADDomainControllerProperties/MSFT_ADDomainControllerProperties.schema.mof
  DSCResources/MSFT_ADDomainControllerProperties/README.md
  DSCResources/MSFT_ADDomainControllerProperties/en-US/MSFT_ADDomainControllerProperties.strings.psd1
  DSCResources/MSFT_ADDomainControllerProperties/en-US/about_ADDomainControllerProperties.help.txt
  Examples/README.md
  Examples/Resources/ADDomainControllerProperties/1-ADDomainControllerProperties_SetContentFreshness_Config.ps1
  Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
  Tests/Integration/MSFT_ADDomainControllerProperties.Integration.Tests.ps1
  Tests/Integration/MSFT_ADDomainControllerProperties.config.ps1
  Tests/Integration/MSFT_ADObjectEnabledState.config.ps1
  Tests/Unit/ActiveDirectory.Common.Tests.ps1
  Tests/Unit/MSFT_ADDomainControllerProperties.Tests.ps1
  Tests/Unit/MSFT_ADObjectEnabledState.Tests.ps1
Labels: needs review

#475 ADForestFunctionalLevel: New resource
  CHANGELOG.md
  DSCResources/MSFT_ADForestFunctionalLevel/MSFT_ADForestFunctionalLevel.psm1
  DSCResources/MSFT_ADForestFunctionalLevel/MSFT_ADForestFunctionalLevel.schema.mof
  DSCResources/MSFT_ADForestFunctionalLevel/README.md
  DSCResources/MSFT_ADForestFunctionalLevel/en-US/MSFT_ADForestFunctionalLevel.strings.psd1
  DSCResources/MSFT_ADForestFunctionalLevel/en-US/about_ADForestFunctionalLevel.help.txt
  Examples/README.md
  Examples/Resources/ADForestFunctionalLevel/1-ADForestFunctionalLevel_SetLevel_Config.ps1
  Tests/Integration/MSFT_ADForestFunctionalLevel.Integration.Tests.ps1
  Tests/Integration/MSFT_ADForestFunctionalLevel.config.ps1
  Tests/Unit/MSFT_ADForestFunctionalLevel.Tests.ps1
  Tests/Unit/Stubs/ActiveDirectoryStub.psm1
Labels: ready for merge

#480 xWaitForADDomain: Correct Grammar Issues in Example Descriptions
  CHANGELOG.md
  Examples/Resources/WaitForADDomain/1-WaitForADDomain_WaitForDomainController_Config.ps1
  Examples/Resources/WaitForADDomain/2-WaitForADDomain_WaitForDomainControllerUsingBuiltInCredential_Config.ps1
  Examples/Resources/WaitForADDomain/3-WaitForADDomain_WaitForDomainControllerUsingCredential_Config.ps1
  Examples/Resources/WaitForADDomain/4-WaitForADDomain_WaitForDomainControllerInSite_Config.ps1
  Examples/Resources/WaitForADDomain/5-WaitForADDomain_WaitForDomainControllerWithReboot_Config.ps1
  Examples/Resources/WaitForADDomain/6-WaitForADDomain_WaitForDomainControllerWithLongerDelay_Config.ps1
Labels: needs review

#479 ActiveDirectoryDsc: Split tests in different AppVeyor jobs
  CHANGELOG.md
  DSCResources/MSFT_ADDomainDefaultPasswordPolicy/MSFT_ADDomainDefaultPasswordPolicy.psm1
  DSCResources/MSFT_ADDomainFunctionalLevel/en-US/about_ADDomainFunctionalLevel.help.txt
  DSCResources/MSFT_ADForestFunctionalLevel/en-US/about_ADForestFunctionalLevel.help.txt
  DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1
  DSCResources/MSFT_ADManagedServiceAccount/MSFT_ADManagedServiceAccount.psm1
  DSCResources/MSFT_WaitForADDomain/en-US/about_WaitForADDomain.help.txt
  Tests/TestHelpers/ActiveDirectoryDsc.TestHelper.psm1
  Tests/Unit/ActiveDirectory.Common.Tests.ps1
  Tests/Unit/MSFT_ADComputer.Tests.ps1
  Tests/Unit/MSFT_ADDomain.Tests.ps1
  Tests/Unit/MSFT_ADDomainController.Tests.ps1
  Tests/Unit/MSFT_ADDomainControllerProperties.Tests.ps1
  Tests/Unit/MSFT_ADDomainDefaultPasswordPolicy.Tests.ps1
  Tests/Unit/MSFT_ADDomainFunctionalLevel.Tests.ps1
  Tests/Unit/MSFT_ADDomainTrust.Tests.ps1
  Tests/Unit/MSFT_ADForestProperties.Tests.ps1
  Tests/Unit/MSFT_ADGroup.Tests.ps1
  Tests/Unit/MSFT_ADKDSKey.Tests.ps1
  Tests/Unit/MSFT_ADManagedServiceAccount.Tests.ps1
  Tests/Unit/MSFT_ADObjectEnabledState.Tests.ps1
  Tests/Unit/MSFT_ADObjectPermissionEntry.Tests.ps1
  Tests/Unit/MSFT_ADOptionalFeature.Tests.ps1
  Tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1
  Tests/Unit/MSFT_ADReplicationSite.Tests.ps1
  Tests/Unit/MSFT_ADReplicationSiteLink.tests.ps1
  Tests/Unit/MSFT_ADReplicationSubnet.Tests.ps1
  Tests/Unit/MSFT_ADServicePrincipalName.Tests.ps1
  Tests/Unit/MSFT_ADUser.Tests.ps1
  Tests/Unit/MSFT_WaitForADDomain.Tests.ps1
  Tests/Unit/Stubs/ActiveDirectoryStub.psm1
  Tests/Unit/Stubs/Microsoft.ActiveDirectory.Management.cs
  appveyor.yml
Labels: ready for merge

#482 ActiveDirectoryDsc: Move unit test to correct appveyor job
  Tests/Unit/MSFT_ADDomainFunctionalLevel.Tests.ps1
  Tests/Unit/MSFT_ADForestFunctionalLevel.Tests.ps1
Labels: needs review

#484 Update CHANGELOG.md
  CHANGELOG.md
Labels: needs review

#485 ADDomain: Get-TargetResource have correct functionality
  CHANGELOG.md
  DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1
  DSCResources/MSFT_ADDomain/MSFT_ADDomain.schema.mof
  DSCResources/MSFT_ADDomain/en-US/MSFT_ADDomain.strings.psd1
  DSCResources/MSFT_ADDomain/en-US/about_ADDomain.help.txt
  Tests/Unit/MSFT_ADDomain.Tests.ps1
Labels: needs review

#483 ActiveDirectoryDsc: Add stubs generated by Indented.StubCommand
  CHANGELOG.md
  Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
  Tests/Unit/ActiveDirectory.Common.Tests.ps1
  Tests/Unit/MSFT_ADComputer.Tests.ps1
  Tests/Unit/MSFT_ADDomain.Tests.ps1
  Tests/Unit/MSFT_ADDomainController.Tests.ps1
  Tests/Unit/MSFT_ADDomainDefaultPasswordPolicy.Tests.ps1
  Tests/Unit/MSFT_ADDomainFunctionalLevel.Tests.ps1
  Tests/Unit/MSFT_ADForestFunctionalLevel.Tests.ps1
  Tests/Unit/MSFT_ADForestProperties.Tests.ps1
  Tests/Unit/MSFT_ADGroup.Tests.ps1
  Tests/Unit/MSFT_ADKDSKey.Tests.ps1
  Tests/Unit/MSFT_ADManagedServiceAccount.Tests.ps1
  Tests/Unit/MSFT_ADObjectEnabledState.Tests.ps1
  Tests/Unit/MSFT_ADObjectPermissionEntry.Tests.ps1
  Tests/Unit/MSFT_ADOptionalFeature.Tests.ps1
  Tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1
  Tests/Unit/MSFT_ADReplicationSite.Tests.ps1
  Tests/Unit/MSFT_ADReplicationSiteLink.tests.ps1
  Tests/Unit/MSFT_ADReplicationSubnet.Tests.ps1
  Tests/Unit/MSFT_ADServicePrincipalName.Tests.ps1
  Tests/Unit/MSFT_ADUser.Tests.ps1
  Tests/Unit/Stubs/ADDSDeployment_2019.psm1
  Tests/Unit/Stubs/ActiveDirectoryStub.psm1
  Tests/Unit/Stubs/ActiveDirectory_2019.psm1
  Tests/Unit/Stubs/Microsoft.ActiveDirectory.Management.cs
  Tests/Unit/Stubs/Microsoft.DirectoryServices.Deployment.Types.cs
  Tests/Unit/Stubs/README.md
Labels: needs review

#487 ADUser: Remove unused non-mandatory parameters from the Get-TargetResource
  CHANGELOG.md
  DSCResources/MSFT_ADUser/MSFT_ADUser.psm1
  Tests/Unit/MSFT_ADUser.Tests.ps1
Labels: needs review

#439 ADDomainController: Added InstallDns to promote without installing DNS
  CHANGELOG.md
  DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.psm1
  DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.schema.mof
  DSCResources/MSFT_ADDomainController/README.md
  DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt
  DSCResources/MSFT_WaitForADDomain/en-US/about_WaitForADDomain.help.txt
  Examples/Resources/ADDomainController/6-ADDomainController_AddDomainControllerUsingInstallDns_Config.ps1
  Examples/Resources/WaitForADDomain/7-WaitForADDomain_WaitForDomainControllerIgnoringAuthenticationErrors_Config.ps1
  Tests/Unit/MSFT_ADDomainController.Tests.ps1
Labels: ready for merge
