Repository dsccommunity/ActiveDirectoryDsc, pull requests merged in 2019-09, with the labels that each got.

#495 ADGroup: Add integration tests
  CHANGELOG.md
  DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1
  Tests/Integration/MSFT_ADGroup.Integration.Tests.ps1
  Tests/Integration/MSFT_ADGroup.config.ps1
Labels: ready for merge

#497 ADGroup: Fix issue #151, issue #189, issue #493
  CHANGELOG.md
  DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt
  DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1
  DSCResources/MSFT_ADGroup/MSFT_ADGroup.schema.mof
  DSCResources/MSFT_ADGroup/en-US/MSFT_ADGroup.strings.psd1
  DSCResources/MSFT_ADGroup/en-US/about_ADGroup.help.txt
  Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
  Modules/ActiveDirectoryDsc.Common/en-US/ActiveDirectoryDsc.Common.strings.psd1
  Tests/Integration/MSFT_ADGroup.Integration.Tests.ps1
  Tests/Integration/MSFT_ADGroup.config.ps1
  Tests/Unit/ActiveDirectory.Common.Tests.ps1
  Tests/Unit/MSFT_ADGroup.Tests.ps1
Labels: ready for merge

#499 Update documentation for resource that uses RestoreFromRecycleBin
  CHANGELOG.md
  DSCResources/MSFT_ADComputer/README.md
  DSCResources/MSFT_ADComputer/en-US/about_ADComputer.help.txt
  DSCResources/MSFT_ADGroup/README.md
  DSCResources/MSFT_ADGroup/en-US/about_ADGroup.help.txt
  DSCResources/MSFT_ADOrganizationalUnit/README.md
  DSCResources/MSFT_ADOrganizationalUnit/en-US/about_ADOrganizationalUnit.help.txt
  DSCResources/MSFT_ADUser/README.md
  DSCResources/MSFT_ADUser/en-US/about_ADUser.help.txt
  Tests/Integration/MSFT_ADComputer.Integration.Tests.ps1
  Tests/Integration/MSFT_ADComputer.config.ps1
  Tests/Integration/MSFT_ADGroup.Integration.Tests.ps1
  Tests/Integration/MSFT_ADGroup.config.ps1
Labels: ready for merge

#501 AdReplicationSite: Adding description attribute, will create integration tests
  CHANGELOG.md
  DSCResources/MSFT_ADReplicationSite/MSFT_ADReplicationSite.psm1
  DSCResources/MSFT_ADReplicationSite/MSFT_ADReplicationSite.schema.mof
  DSCResources/MSFT_ADReplicationSite/en-US/MSFT_ADReplicationSite.strings.psd1
  DSCResources/MSFT_ADReplicationSite/en-US/about_ADReplicationSite.help.txt
  Tests/Integration/MSFT_ADReplicationSite.Integration.Tests.ps1
  Tests/Integration/MSFT_ADReplicationSite.config.ps1
  Tests/Unit/MSFT_ADReplicationSite.Tests.ps1
Labels: ready for merge

#508 ActiveDirectoryDsc: Resolved custom Script Analyzer rules
  CHANGELOG.md
  DSCResources/MSFT_ADUser/MSFT_ADUser.psm1
Labels: needs review

#507 ADReplicationSubnet: Add Integration Testing, Add Description
  CHANGELOG.md
  DSCResources/MSFT_ADReplicationSubnet/MSFT_ADReplicationSubnet.psm1
  DSCResources/MSFT_ADReplicationSubnet/MSFT_ADReplicationSubnet.schema.mof
  DSCResources/MSFT_ADReplicationSubnet/en-US/MSFT_ADReplicationSubnet.strings.psd1
  DSCResources/MSFT_ADReplicationSubnet/en-US/about_ADReplicationSubnet.help.txt
  Examples/Resources/ADReplicationSubnet/1-ADReplicationSubnet_CreateReplicationSubnet_Config.ps1
  Tests/Integration/MSFT_ADReplicationSubnet.Integration.Tests.ps1
  Tests/Integration/MSFT_ADReplicationSubnet.config.ps1
  Tests/Unit/MSFT_ADReplicationSubnet.Tests.ps1
Labels: waiting for code fix
