Repository dsccommunity/ActiveDirectoryDsc, pull requests merged in 2019-10, with the labels that each got.

#514 ActiveDirectoryDsc.Common: Fix Test-DscPropertyState Failing when Comparing $Null and Arrays
  CHANGELOG.md
  Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
  Tests/Unit/ActiveDirectory.Common.Tests.ps1
Labels: needs review

#509 ADReplicationSiteLink: Add Integration tests, add setting 'options'
  CHANGELOG.md
  DSCResources/MSFT_ADReplicationSiteLink/MSFT_ADReplicationSiteLink.psm1
  DSCResources/MSFT_ADReplicationSiteLink/MSFT_ADReplicationSiteLink.schema.mof
  DSCResources/MSFT_ADReplicationSiteLink/en-US/about_ADReplicationSiteLink.help.txt
  Examples/Resources/ADReplicationSiteLink/3-ADReplicationSiteLink_EnableOptions_Config.ps1
  Tests/Integration/MSFT_ADReplicationSiteLink.Integration.Tests.ps1
  Tests/Integration/MSFT_ADReplicationSiteLink.config.ps1
  Tests/Unit/MSFT_ADReplicationSiteLink.tests.ps1
Labels: ready for merge

#521 Resolve style guideline violations for hashtables
  CHANGELOG.md
  DSCResources/MSFT_ADComputer/MSFT_ADComputer.psm1
  DSCResources/MSFT_ADDomainTrust/MSFT_ADDomainTrust.psm1
  DSCResources/MSFT_ADForestProperties/MSFT_ADForestProperties.psm1
  DSCResources/MSFT_ADReplicationSiteLink/MSFT_ADReplicationSiteLink.psm1
  DSCResources/MSFT_ADServicePrincipalName/MSFT_ADServicePrincipalName.psm1
  DSCResources/MSFT_ADUser/MSFT_ADUser.psm1
Labels: waiting for code fix
