Repository dsccommunity/ActiveDirectoryDsc, pull requests merged in 2020-02, with the labels that each got.

#555 ADObjectPermissionEntry: Fix Exception When the Object Path Does Not Exist
  CHANGELOG.md
  Tests/Unit/MSFT_ADObjectPermissionEntry.Tests.ps1
  source/DSCResources/MSFT_ADObjectPermissionEntry/MSFT_ADObjectPermissionEntry.psm1
  source/DSCResources/MSFT_ADObjectPermissionEntry/en-US/MSFT_ADObjectPermissionEntry.strings.psd1
Labels: needs review

#557 ActiveDirectoryDsc: Update License Copyright to Dsc Community Contributors
  CHANGELOG.md
  LICENSE
Labels: needs review

#562 ActiveDirectoryDsc: Enable Codecov.io Support in the CI Pipeline
  CHANGELOG.md
  README.md
  azure-pipelines.yml
  build.yaml
  codecov.yml
Labels: needs review

#559 ADOrganizationalUnit: Fix Get-TargetResource Exception when Path does not Exist
  CHANGELOG.md
  Tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1
  source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1
  source/DSCResources/MSFT_ADOrganizationalUnit/en-US/MSFT_ADOrganizationalUnit.strings.psd1
Labels: waiting for code fix

#567 ActiveDirectoryDsc: Fix Spelling Errors
  CHANGELOG.md
  source/DSCResources/MSFT_ADDomainFunctionalLevel/README.md
  source/DSCResources/MSFT_ADDomainFunctionalLevel/en-US/about_ADDomainFunctionalLevel.help.txt
  source/DSCResources/MSFT_ADForestFunctionalLevel/README.md
  source/DSCResources/MSFT_ADForestFunctionalLevel/en-US/about_ADForestFunctionalLevel.help.txt
  source/DSCResources/MSFT_ADServicePrincipalName/MSFT_ADServicePrincipalName.psm1
  source/DSCResources/MSFT_ADServicePrincipalName/MSFT_ADServicePrincipalName.schema.mof
  source/DSCResources/MSFT_ADServicePrincipalName/en-US/about_ADServicePrincipalName.help.txt
Labels: needs review

#566 BREAKING CHANGE: ADDomain: Change Domain Install Tracking File to NetLogon Registry Test and Refactor
  .markdownlint.json
  CHANGELOG.md
  Tests/Integration/MSFT_ADDomain.Child.Integration.Tests.ps1
  Tests/Integration/MSFT_ADDomain.Child.config.ps1
  Tests/Integration/MSFT_ADDomain.Root.Integration.Tests.ps1
  Tests/Integration/MSFT_ADDomain.Root.config.ps1
  Tests/Unit/MSFT_ADDomain.Tests.ps1
  source/ActiveDirectoryDsc.psd1
  source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1
  source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.schema.mof
  source/DSCResources/MSFT_ADDomain/en-US/MSFT_ADDomain.strings.psd1
  source/DSCResources/MSFT_ADDomain/en-US/about_ADDomain.help.txt
  source/Examples/Resources/ADDomain/2-ADDomain_NewChildDomain_Config.ps1
Labels: ready for merge

#568 ActiveDirectoryDsc: Add StrictMode v1.0 to all Unit Tests
  CHANGELOG.md
  Tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1
  Tests/Unit/MSFT_ADComputer.Tests.ps1
  Tests/Unit/MSFT_ADDomainController.Tests.ps1
  Tests/Unit/MSFT_ADDomainControllerProperties.Tests.ps1
  Tests/Unit/MSFT_ADDomainDefaultPasswordPolicy.Tests.ps1
  Tests/Unit/MSFT_ADDomainFunctionalLevel.Tests.ps1
  Tests/Unit/MSFT_ADForestFunctionalLevel.Tests.ps1
  Tests/Unit/MSFT_ADGroup.Tests.ps1
  Tests/Unit/MSFT_ADKDSKey.Tests.ps1
  Tests/Unit/MSFT_ADManagedServiceAccount.Tests.ps1
  Tests/Unit/MSFT_ADObjectEnabledState.Tests.ps1
  Tests/Unit/MSFT_ADObjectPermissionEntry.Tests.ps1
  Tests/Unit/MSFT_ADOptionalFeature.Tests.ps1
  Tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1
  Tests/Unit/MSFT_ADReplicationSite.Tests.ps1
  Tests/Unit/MSFT_ADReplicationSiteLink.tests.ps1
  Tests/Unit/MSFT_ADReplicationSubnet.Tests.ps1
  Tests/Unit/MSFT_ADServicePrincipalName.Tests.ps1
  Tests/Unit/MSFT_ADUser.Tests.ps1
  Tests/Unit/MSFT_WaitForADDomain.Tests.ps1
  source/DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1
  source/DSCResources/MSFT_ADManagedServiceAccount/MSFT_ADManagedServiceAccount.psm1
  source/DSCResources/MSFT_ADObjectPermissionEntry/MSFT_ADObjectPermissionEntry.psm1
  source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1
  source/DSCResources/MSFT_ADReplicationSiteLink/MSFT_ADReplicationSiteLink.psm1
  source/DSCResources/MSFT_ADUser/MSFT_ADUser.psm1
  source/DSCResources/MSFT_WaitForADDomain/MSFT_WaitForADDomain.psm1
  source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
Labels: ready for merge
