Repository dsccommunity/ActiveDirectoryDsc, pull requests merged in 2022-05, with the labels that each got.

#664 ADOrganizationalUnit: add property "RestoreFromRecycleBin" to ignorelist
  CHANGELOG.md
  source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1
  tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1
Labels: needs review

#649 ADKDSKey: Fixes #648, the resource did not work due to a non-working date conversion
  CHANGELOG.md
  source/DSCResources/MSFT_ADKDSKey/MSFT_ADKDSKey.psm1
Labels: ready for merge

#661 ADManagedServiceAccount: Add CommonName parameter
  CHANGELOG.md
  source/DSCResources/MSFT_ADManagedServiceAccount/MSFT_ADManagedServiceAccount.psm1
  source/DSCResources/MSFT_ADManagedServiceAccount/MSFT_ADManagedServiceAccount.schema.mof
  tests/Integration/MSFT_ADManagedServiceAccount.Integration.Tests.ps1
  tests/Integration/MSFT_ADManagedServiceAccount.config.ps1
  tests/Unit/MSFT_ADManagedServiceAccount.Tests.ps1
Labels: needs review

#686 Fix ad domain controller
  CHANGELOG.md
  source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1
  source/DSCResources/MSFT_ADDomain/en-US/MSFT_ADDomain.strings.psd1
  source/DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.psm1
  source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psd1
  source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1
  source/Modules/ActiveDirectoryDsc.Common/README.md
  source/Modules/ActiveDirectoryDsc.Common/docs/Get-DomainObject.md
  source/Modules/ActiveDirectoryDsc.Common/en-US/ActiveDirectoryDsc.Common.strings.psd1
  tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1
  tests/Unit/MSFT_ADDomain.Tests.ps1
  tests/Unit/MSFT_ADDomainController.Tests.ps1
Labels: waiting for code fix

#687 Remove pipeline file no longer required
  CHANGELOG.md
  source/build.psd1
Labels: needs review

#666 ADOrganizationalUnit: Added DomainController Parameter #563
  CHANGELOG.md
  source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1
  source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.schema.mof
  source/DSCResources/MSFT_ADOrganizationalUnit/en-US/about_ADOrganizationalUnit.help.txt
  tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1
Labels: needs review
